"""MobiusSec — Unified Mobile Security Platform."""

__version__ = "0.1.0"

# MASVS 2.0 Categories
MASVS_STORAGE = "STORAGE"
MASVS_CRYPTO = "CRYPTO"
MASVS_AUTH = "AUTH"
MASVS_NETWORK = "NETWORK"
MASVS_PLATFORM = "PLATFORM"
MASVS_CODE = "CODE"
MASVS_RESILIENCE = "RESILIENCE"
MASVS_PRIVACY = "PRIVACY"

MASVS_CATEGORIES = [
    MASVS_STORAGE,
    MASVS_CRYPTO,
    MASVS_AUTH,
    MASVS_NETWORK,
    MASVS_PLATFORM,
    MASVS_CODE,
    MASVS_RESILIENCE,
    MASVS_PRIVACY,
]

# Severity levels
SEVERITY_CRITICAL = "critical"
SEVERITY_HIGH = "high"
SEVERITY_MEDIUM = "medium"
SEVERITY_LOW = "low"
SEVERITY_INFO = "info"

SEVERITY_ORDER = {
    SEVERITY_CRITICAL: 0,
    SEVERITY_HIGH: 1,
    SEVERITY_MEDIUM: 2,
    SEVERITY_LOW: 3,
    SEVERITY_INFO: 4,
}

# Platform types
PLATFORM_ANDROID = "android"
PLATFORM_IOS = "ios"
PLATFORM_UNKNOWN = "unknown"